---
# Enable the serial port console and login
- include: serial_port_console.yaml
  
- name: install tools
  yum:
    name:
      - tmux 
      - nmap
      - traceroute
      - bind-utils
      - openldap-clients
      - tcpdump
      - strace
    state: present

# Install and configure libvirt, pools and networks
- include: libvirt.yaml

# ============================================================================
# Network interfaces and bridges
# ============================================================================
- include: networks_nmcli.yaml

# ============================================================================
# Prepare stack user
# ============================================================================
- name: add stack user
  user:
    name: stack
    generate_ssh_key: true
    state: present
