---
# Enable the serial port console and login
- include: serial_port_console.yaml
  
- name: install tools
  yum:
    name:
      - tmux 
      - nmap
      - traceroute
      - bind-utils
      - openldap-clients
      - tcpdump
      - strace
      - python3-pip
      - python3-jinja2
      - podman-docker
    state: present

- name: install pip tools
  pip:
    name: jinja2-cli
    extra_args: --user
    state: present

# ============================================================================
# Network interfaces and bridges
# ============================================================================
- include: networks_nmcli.yaml

# Install and configure libvirt, pools and networks
- include: libvirt.yaml

# Configure DNS for the cluster
- include: coredns.yaml
