---
# Enable the serial port console and login
- include: serial_port_console.yaml
  
- name: install tools
  yum:
    name:
      - tmux 
      - nmap
      - traceroute
      - bind-utils
      - openldap-clients
      - tcpdump
      - strace
      - python3-pip
      - python3-jinja2
      - podman-docker
    state: present

- name: install pip tools
  pip:
    name: jinja2-cli
    extra_args: --user
    state: present

# ============================================================================
# Network interfaces and bridges
# ============================================================================
- include: networks_nmcli.yaml

# Install and configure libvirt, pools and networks
- include: libvirt.yaml

# Configure DNS for the cluster
- include: coredns.yaml

- name: enable inbound NTP connections
  firewalld:
    zone: public
    service: ntp
    state: enabled

- name: enable chrony listener on prov network
  lineinfile: 
    backup: true
    insertafter: "^# Allow NTP client access from local network."
    state: present
    line: "allow 172.16.3.0/24"
    path: /etc/chrony.conf
 
- name: start chrony service
  service:
    name: chronyd
    state: started
    enabled: yes
