# ============================================================================
# Network interfaces and bridges
# ============================================================================

- name: Add resolver to global dns
  lineinfile:
    path: /etc/systemd/resolved.conf
    insertafter: "^[Resolve]"
    regexp: "^#?DNS="
    line: DNS=192.168.1.1
  notify: restart resolved
  
- name: Add search domains to global dns
  lineinfile:
    path: /etc/systemd/resolved.conf
    insertafter: "^[Resolve]"
    regexp: "^#?Domains="
    line: Domains=lamourine.org
  notify: restart resolved
    
# Add the external bridge 
# - name: ext bridge
#   community.general.nmcli:
#     conn_name: br-ext
#     ifname: br-ext
#     type: bridge
#     autoconnect: yes
#     ip4: 192.168.1.100/24
#     gw4: 192.168.1.1
#     dns4: 192.168.1.1
#     dns4_search: lamourine.org
#     state: present

# - name: ext bridge-slave ("{{ ext_interface }}")
#   community.general.nmcli:
#     conn_name: "{{ ext_interface }}"
#     ifname: "{{ ext_interface }}"
#     type: bridge-slave
#     master: br-ext
#     autoconnect: yes
#     state: present

Add the IPMI network for control of hardware
- name: ipmi bridge
  community.general.nmcli:
    conn_name: br-ipmi
    ifname: br-ipmi
    type: bridge
    autoconnect: yes
    ip4: 172.16.2.2/24
    state: absent

- name: ipmi bridge-slave ("{{ ipmi_interface }}")
  community.general.nmcli:
    conn_name: "{{ ipmi_interface }}"
    ifname: "{{ ipmi_interface }}"
    type: bridge-slave
    master: br-ipmi
    autoconnect: yes
    state: absent

# Add the Prov network for control plane and provisioning
- name: prov bridge
  community.general.nmcli:
    conn_name: br-prov
    ifname: br-prov
    type: bridge
    autoconnect: yes
    ip4: 172.16.3.2/24
    state: absent

- name: prov bridge-slave ("{{ prov_interface }}")
  community.general.nmcli:
    conn_name: "{{ prov_interface }}"
    ifname: "{{ prov_interface }}"
    type: bridge-slave
    master: br-prov
    autoconnect: yes
    state: absent

# Add the data network for storage and tenant traffic
- name: data bridge
  community.general.nmcli:
    conn_name: br-data
    ifname: br-data
    type: bridge
    autoconnect: yes
    ip4: 172.16.4.2/24
    state: absent

- name: data bridge-slave ("{{ data_interface }}")
  community.general.nmcli:
    conn_name: "{{ data_interface }}"
    ifname: "{{ data_interface }}"
    type: bridge-slave
    master: br-data
    autoconnect: yes
    state: absent
